nameOverride: demo-web
replicaCount: 2
controller:
  labels:
    environment: stage
    stack: demo
    component: demo-web
podLabels:
  environment: stage
  stack: demo
  component: demo-web
image:
  repository: pok1sdiplomaacr.azurecr.io/diploma-demo-web
  tag: stage-4a7f710-4
config:
  APP_NAME: diploma-demo-web
  APP_ENV: stage
  APP_VERSION: stage-4a7f710-4
  DEPLOYMENT_TIMESTAMP: '2026-05-06T23:01:44Z'
  GIT_SHA: 4a7f710ddb4b016a908232347ebdf972ce1be81a
  PORT: '8080'
secret:
  enabled: true
  data:
    EXAMPLE_API_TOKEN: demo-token-stage
ingress:
  enabled: true
  className: nginx
  host: stage.diploma-demo.local
resources:
  requests:
    cpu: 75m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 384Mi
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuAverageUtilization: 65
