nameOverride: demo-web
replicaCount: 3
controller:
  labels:
    environment: prod
    stack: demo
    component: demo-web
podLabels:
  environment: prod
  stack: demo
  component: demo-web
image:
  repository: pok1sdiplomaacr.azurecr.io/diploma-demo-web
  tag: prod-9a12f8d-7
config:
  APP_NAME: diploma-demo-web
  APP_ENV: prod
  APP_VERSION: prod-9a12f8d-7
  DEPLOYMENT_TIMESTAMP: '2026-05-06T23:17:06Z'
  GIT_SHA: 9a12f8da75adbf79b6cf108df70dda6559aa7d09
  PORT: '8080'
secret:
  enabled: true
  data:
    EXAMPLE_API_TOKEN: demo-token-prod
ingress:
  enabled: true
  className: nginx
  host: diploma-demo.local
resources:
  requests:
    cpu: 100m
    memory: 160Mi
  limits:
    cpu: 750m
    memory: 512Mi
hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  cpuAverageUtilization: 60
